version: '3'
services:
  postgres:
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
